default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fukusuke_development

test:
  <<: *default
  database: fukusuke_test

production:
  <<: *default
  database: fukusuke_production
  username: fukusuke
  password: <%= ENV['FUKUSUKE_DATABASE_PASSWORD'] %>
